config/routes.rb
Rails.application.routes.draw do

  root 'welcome#index'  
  
  resources :cars do
    resources :listing_details, only: [:create]
  end

  resources :photos

  resources :cars do
    resources :reservations, only: [:create]
  end

  get '/preload' => 'reservations#preload'
  get '/preview' => 'reservations#preview'

  get '/your_trips' => 'reservations#your_trips'
  get '/your_reservations' => 'reservations#your_reservations'

  get '/about', to: 'static_pages#about'
  get '/contact', to: 'static_pages#contact'
  get '/terms_and_conditions',  to: 'static_pages#terms_and_conditions'

  
  mount RailsAdmin::Engine => '/admin', as: 'rails_admin'
  scope :users do 
    get '/profile', to: 'profiles#index'
  	get '/profile/:id/edit', to: 'profiles#edit'
    put '/profile/:id', to: 'profiles#update'
    post '/profile', to: 'profiles#attach_file', as: 'user_attachments'
  end

  devise_for :users,
  					 :controllers => {:registrations => 'registrations'}

  scope '/admin' do
  	get '/archives', to: 'archives#index'
  	post '/archives', to: 'archives#import', as: 'file_import'
  end

  # For details on the DSL available within this file, see http://guides.rubyonrails.org/routing.html
  #match ':controller(/:action(/:id))', :via => [:get, :post, :put]
end

app/models/ability.rb
class Ability
  include CanCan::Ability

  def initialize(user)
    # Define abilities for the passed in user here. For example:
    #
    #   user ||= User.new # guest user (not logged in)
    #   if user.admin?
    #     can :manage, :all
    #   else
    #     can :read, :all
    #   end
    #
    # The first argument to `can` is the action you are giving the user
    # permission to do.
    # If you pass :manage it will apply to every action. Other common actions
    # here are :read, :create, :update and :destroy.
    #
    # The second argument is the resource the user can perform the action on.
    # If you pass :all it will apply to every resource. Otherwise pass a Ruby
    # class of the resource.
    #
    # The third argument is an optional hash of conditions to further filter the
    # objects.
    # For example, here the user can only update published articles.
    #
    #   can :update, Article, :published => true
    #
    # See the wiki for details:
    # https://github.com/CanCanCommunity/cancancan/wiki/Defining-Abilities
    can :read, :all                   # allow everyone to read everything
    if user && user.has_role?(:admin)
      if user.role? :superadmin
        can :manage, :all             # allow superadmins to do anything
      #elsif user.role? :owner
      #  can :manage, [User, Product]  # allow managers to do anything to products and users
      #elsif user.role? :renter
      #  can :update, Product, :hidden => false  # allow sales to only update visible products
      end
    end

    # Todos:
    # can :manage, Article  # user can perform any action on the article
    # can :read, :all       # user can read any object
    # can :manage, :all     # user can perform any action on any object

  end
end

app/models/admin_ability.rb
class AdminAbility
  include CanCan::Ability
  def initialize(user)
    if user && user.has_role?(:admin)
      can :access, :rails_admin
      can :manage, :all   
    end
  end
end

app/models/car.rb
class Car < ApplicationRecord
  belongs_to :user
  belongs_to :fuel_type
  belongs_to :car_model
  belongs_to :car_make
  belongs_to :transmission_type
  belongs_to :vehicle_type
  has_one    :listing_detail
  has_many  :photos
  has_many :reservations

  validates :vehicle_type_id,  presence: true
  validates :capacity,  presence: true
  validates :year,  presence: true
  #validates :car_model_id,  presence: true
  validates :transmission_type_id,  presence: true
  validates :fuel_type_id,  presence: true
  validates :color,  presence: true
  validates :mileage,  presence: true
  #validates :car_make_id,  presence: true
  accepts_nested_attributes_for :listing_detail
  #mount_uploaders :car_photos, CarPhotoUploader
  #validate :image_size_validation

  accepts_nested_attributes_for :listing_detail, :reject_if => :all_blank
  
  private
    #def image_size_validation
    #  errors[:car_photos] << "should be less than 500KB" if car_photos.size > 0.5.megabytes
    #end
end

app/models/car_make.rb
class CarMake < ApplicationRecord
  has_many :car_models
  validates :make, presence: true, length: { minimum: 2, maximum: 25 }
  validates_uniqueness_of :make, :case_sensitive => false
end

app/models/car_model.rb
class CarModel < ApplicationRecord
  belongs_to :car_make
  validates :model, presence: true
  validates_uniqueness_of :model, :case_sensitive => false
end

app/models/delivery_option.rb
class DeliveryOption < ApplicationRecord
  validates :description, presence: true, length: { minimum: 3, maximum: 25 }
  validates_uniqueness_of :description
end

app/models/driving_rule.rb
class DrivingRule < ApplicationRecord
  validates :description, presence: true, length: { minimum: 3, maximum: 30 }
  validates_uniqueness_of :description
end

app/models/fuel_type.rb
class FuelType < ApplicationRecord
  validates :description, presence: true, length: { minimum: 3, maximum: 25 }
  validates_uniqueness_of :description
end

app/models/listing_detail.rb
class ListingDetail < ApplicationRecord
  belongs_to :car
  belongs_to :payment_method 
  belongs_to :delivery_option 
  belongs_to :payment_frequency 
  belongs_to :driving_rule

  validates :operator_name,  presence: true 
  validates :operator_ci,  presence: true
  validates :comments,  presence: true 
  validates :other_features,  presence: true 
  validates :vehicle_nickname,  presence: true 
  validates :vehicle_relationship,  presence: true 
  validates :driving_rule_id,  presence: true 
  validates :delivery_option_id,  presence: true 
  validates :vehicle_location,  presence: true 
  validates :driver_location,  presence: true 
  validates :payment_frequency_id,  presence: true 
  validates :payment_method_id,  presence: true
  validates :cost_city_driving,  presence: true 
  validates :cost_prov_driving,  presence: true 
  validates :cost_inclusion,  presence: true 
  validates :payment_spec,  presence: true 
  validates :addtl_rule,  presence: true

  geocoded_by :vehicle_location
  after_validation :geocode, if: :vehicle_location?

  
end

app/models/payment_frequency.rb
class PaymentFrequency < ApplicationRecord
  validates :description, presence: true, length: { minimum: 3, maximum: 50 }
  validates :frequency_bit, presence: true
  validates_uniqueness_of :description
end

app/models/payment_method.rb
class PaymentMethod < ApplicationRecord
  validates :description, presence: true, length: { minimum: 3, maximum: 50 }
  validates :payment_bit, presence: true
  validates_uniqueness_of :description
end

app/models/photo.rb
class Photo < ApplicationRecord
  belongs_to :car

  has_attached_file :image, styles: { medium: "300x300>", thumb: "100x100>" }
  validates_attachment_content_type :image, content_type: /\Aimage\/.*\Z/
end

app/models/profile.rb
class Profile < ApplicationRecord
  belongs_to :user, :dependent => :destroy
  mount_uploader :avatar, AvatarUploader
  # attr_accessible :first_name, :last_name, :gender, :phone_number
end

app/models/reservation.rb
#  rails g model Reservation user:references car:references 
#    start_date:date_time end_date:date_time price:integer total:integer 
class Reservation < ApplicationRecord
  belongs_to :user
  belongs_to :car
end

app/models/role.rb
class Role < ApplicationRecord
  has_and_belongs_to_many :users, :join_table => :users_roles

  belongs_to :resource,
             :polymorphic => true,
             :optional => true

  validates :resource_type,
            :inclusion => { :in => Rolify.resource_types },
            :allow_nil => true

  scopify
end

app/models/transmission_type.rb
class TransmissionType < ApplicationRecord
  validates :description, presence: true, length: { minimum: 3, maximum: 25 }
  validates_uniqueness_of :description
end

app/models/user.rb
class User < ApplicationRecord
  rolify
  # Include default devise modules. Others available are:
  # :confirmable, :lockable, :timeoutable and :omniauthable
  devise :database_authenticatable, :registerable,
         :recoverable, :rememberable, :trackable, :validatable
         
  has_one :profile
  accepts_nested_attributes_for :profile
  has_many :cars
  has_many :reservations

end

app/models/vehicle_type.rb
class VehicleType < ApplicationRecord
  validates_uniqueness_of :description, :case_sensitive => false
  validates :description, presence: true, length: { minimum: 3, maximum: 40 }
end

app/controllers/requirements_controller.rb
class RequirementsController < ApplicationController

end

app/helpers/archives_helper.rb
module ArchivesHelper
end

app/helpers/welcome_helper.rb
module WelcomeHelper
end

app/views/requirements/_block_requirements.html.erb
<section class="profile-requirements">

  <header>
    <h3 class="block-header">Requirements Information</h3>
  </header>

  <div class="container-fluid p0">

    <div class="col-sm-12 col-md-6">
      <h3>For Renter</h3>
      <ul class="renter-requirements">
        <li class="req req-ok"> <i data-toggle="tooltip" data-placement="top" title="This requirement has been Verified."></i> Government ID</li>
        <li class="req req-check"> <i data-toggle="tooltip" data-placement="top" title="This requirement is for verification."></i> Passport</li>
        <li class="req req-no"> <i data-toggle="tooltip" data-placement="top" title="You haven't submitted this requirement yet."></i> Latest Billing Statement</li>
        <li class="req req-no"> <i data-toggle="tooltip" data-placement="top" title="You haven't submitted this requirement yet."></i> Driver's License</li>
      </ul>

      <%= render "requirements/renters_requirements" %>
    </div>

    <div class="col-sm-12 col-md-6">
      <h3>For Owner</h3>
      <ul class="owner-requirements">
        <li class="req req-no"> <i data-toggle="tooltip" data-placement="top" title="You haven't submitted this requirement yet."></i> ORCR</li>
        <li class="req req-no"> <i data-toggle="tooltip" data-placement="top" title="You haven't submitted this requirement yet."></i> Latest Insurance Policy</li>
        <li class="req req-no"> <i data-toggle="tooltip" data-placement="top" title="You haven't submitted this requirement yet."></i> TNVS PA</li>
        <li class="req req-no"> <i data-toggle="tooltip" data-placement="top" title="You haven't submitted this requirement yet."></i> TIN</li>
      </ul>

      <%= render "requirements/carowners_requirements" %>
    </div>

    <footer class="form-actions">
      <button class="btn add-req-btn">Add Requirements</button>
      <button class="btn submit-req">Submit Requirements</button>
      <button class="btn btn_cancel">Cancel</button>
    </footer>

  </div>

  <footer>
    
  </footer>

</section>

app/views/requirements/_carowners_requirements.html.erb
<div class="req-add">

	<div class="form-group">
		<label class="label col">ORCR</label>
		<%= form_tag user_attachments_path, method: :post, multipart: true do %>
			<%= file_field_tag 'attachment[orcr]', onchange: 'this.form.submit();' %>
		<% end %>
	</div>

	<div class="form-group">
	  <label class="label col">Latest Insurance Policy</label>
		<%= form_tag user_attachments_path, method: :post, multipart: true do %>
			<%= file_field_tag 'attachment[insurance]', onchange: 'this.form.submit();' %>
		<% end %>
	</div>
	<div class="form-group">
	  <label class="label col">TNVS PA</label>
		<%= form_tag user_attachments_path, method: :post, multipart: true do %>
			<%= file_field_tag 'attachment[tnvs]', onchange: 'this.form.submit();' %>
		<% end %>
	</div>
	<div class="form-group">
	  <label class="label col">TIN</label>
		<%= form_tag user_attachments_path, method: :post, multipart: true do %>
			<%= file_field_tag 'attachment[tin]', onchange: 'this.form.submit();' %>
		<% end %>
	</div>

</div>

app/views/requirements/_drivers_requirements.html.erb
<div class="row">
  <label class="label col">Driver's License</label>
	<%= form_tag user_attachments_path, method: :post, multipart: true do %>
		<label class="upload-attachment">
			<i class="fa fa-plus center"></i>
			<%= file_field_tag 'attachment[license]', onchange: 'this.form.submit();' %>
		</label>
	<% end %>
</div>
<div class="row">
  <label class="label col">NBI Clearance</label>
	<%= form_tag user_attachments_path, method: :post, multipart: true do %>
		<label class="upload-attachment">
			<i class="fa fa-plus center"></i>
			<%= file_field_tag 'attachment[nbi_clearance]', onchange: 'this.form.submit();' %>
		</label>
	<% end %>
</div>
<div class="row">
  <label class="label col">Police Clearance</label>
	<%= form_tag user_attachments_path, method: :post, multipart: true do %>
		<label class="upload-attachment">
			<i class="fa fa-plus center"></i>
			<%= file_field_tag 'attachment[police_clearance]', onchange: 'this.form.submit();' %>
		</label>
	<% end %>
</div>
<div class="row">
  <label class="label col">Medical Certificate</label>
	<%= form_tag user_attachments_path, method: :post, multipart: true do %>
		<label class="upload-attachment">
			<i class="fa fa-plus center"></i>
			<%= file_field_tag 'attachment[med_cert]', onchange: 'this.form.submit();' %>
		</label>
	<% end %>
</div>
<div class="row">
  <label class="label col">TIN</label>
	<%= form_tag user_attachments_path, method: :post, multipart: true do %>
		<label class="upload-attachment">
			<i class="fa fa-plus center"></i>
			<%= file_field_tag 'attachment[tin]', onchange: 'this.form.submit();' %>
		</label>
	<% end %>
</div>

app/views/requirements/_renters_requirements.html.erb
<div class="req-add">	

	<div class="form-group">
	  <label class="label col">Government Id</label>
		<%= form_tag user_attachments_path, method: :post, multipart: true do %>
			<%= file_field_tag 'attachment[gov_id]', onchange: 'this.form.submit();' %>
		<% end %>
	</div>
	<div class="form-group">
	  <label class="label col">Passport</label>
		<%= form_tag user_attachments_path, method: :post, multipart: true do %>
			<%= file_field_tag 'attachment[passport]', onchange: 'this.form.submit();' %>
		<% end %>
	</div>
	<div class="form-group">
	  <label class="label col">Latest Bill</label>
		<%= form_tag user_attachments_path, method: :post, multipart: true do %>
			<%= file_field_tag 'attachment[billing]', onchange: 'this.form.submit();' %>
		<% end %>
	</div>
	<div class="form-group">
	  <label class="label col">Driver's License</label>
		<%= form_tag user_attachments_path, method: :post, multipart: true do %>
			<%= file_field_tag 'attachment[license]', onchange: 'this.form.submit();' %>
		<% end %>
	</div>

</div>