config/routes.rb
Rails.application.routes.draw do

  root 'welcome#index'  
  
  resources :cars do
    resources :listing_details, only: [:create]
  end

  resources :photos

  resources :cars do
    resources :reservations, only: [:create]
  end

  get '/preload' => 'reservations#preload'
  get '/preview' => 'reservations#preview'

  get '/your_trips' => 'reservations#your_trips'
  get '/your_reservations' => 'reservations#your_reservations'

  get '/about', to: 'static_pages#about'
  get '/contact', to: 'static_pages#contact'
  get '/terms_and_conditions',  to: 'static_pages#terms_and_conditions'

  
  mount RailsAdmin::Engine => '/admin', as: 'rails_admin'
  scope :users do 
    get '/profile', to: 'profiles#index'
  	get '/profile/:id/edit', to: 'profiles#edit'
    put '/profile/:id', to: 'profiles#update'
    post '/profile', to: 'profiles#attach_file', as: 'user_attachments'
  end

  devise_for :users,
  					 :controllers => {:registrations => 'registrations'}

  scope '/admin' do
  	get '/archives', to: 'archives#index'
  	post '/archives', to: 'archives#import', as: 'file_import'
  end

  # For details on the DSL available within this file, see http://guides.rubyonrails.org/routing.html
  #match ':controller(/:action(/:id))', :via => [:get, :post, :put]
end

app/controllers/archives_controller.rb
class ArchivesController < ApplicationController

  def index
  end

	def import
		@data = parse_archived(params[:file])
		# parse_and_save_archived(params[:file])
		render :index #, notice: 'File Import Succes'
	end

#######################
## FLOW
#  - import file => validate file => parse => validate elements => render
#  - options to save or update and save
#
#######################
## TODO ?
# => create file validation
# 			=> has one sheet
# 			=> has xls format
# 			=> parsing header
# => create database validation
# 			=> user exist in db?
# => add database validation status in table
# => create controller actions: update(update and save) and save(save_only)
#
#


	private

	def parse_archived(file)
		spreadsheet = Roo::Spreadsheet.open(file.path)
	  header = spreadsheet.row(1)
	  header.each_with_index do |element, index|
	    header[index] = "date_filed" if element == "Timestamp"
	    header[index] = "attribute" if element == "What is your relationship to the vehicle?"
	    header[index] = "rules" if element == "What driving rules are you open for with your vehicle?"
	    header[index] = "delivery" if element == "What delivery options do you prefer?"
	    header[index] = "car_name" if element == "Vehicle Nickname"
	    header[index] = "car_location" if element == "Location of Vehicle"
	    header[index] = "driver_location" if element == "Location of Driver/s"
	    header[index] = "vehicle_types" if element == "Type of Vehicle"
	    header[index] = "car_capacity" if element == "Capacity"
	    header[index] = "car_make" if element == "Make"
	    header[index] = "car_year" if element == "Year"
	    header[index] = "car_model" if element == "Model"
	    header[index] = "car_transmission" if element == "Transmission"
	    header[index] = "car_fuel" if element == "Fuel"
	    header[index] = "car_color" if element == "Color"
	    header[index] = "car_mileage" if element == "Mileage (for automobiles)"
	    header[index] = "car_other_feature" if element == "Other features/specifications/uniqueness"
	    header[index] = "payment_freq" if element == "Payment Frequency"
	    header[index] = "payment_method" if element == "Payment Method"
	    header[index] = "price_city" if element == "Cost/Price for City Driving"
	    header[index] = "price_province" if element == "Cost/Price for Provincial Driving"
	    header[index] = "cost_inclusion" if element == "Cost inclusions"
	    header[index] = "payment_condition" if element == "Additional payment specifications"
	    header[index] = "rules_addition" if element == "Additional rules/preferences/notes for the renter"
	    header[index] = "user_full_name" if element == "Car Owner's Full Name"
	    header[index] = "user_email" if element == "Car Owner's Email"
	    header[index] = "user_number" if element == "Car Owner's Contact Number"
	    # header[index] = "logic" if element == "Operator's Name"
	    # header[index] = "logic" if element == "Operator's Contact Information"
	    header[index] = "user_comment" if element == "Additional comment/request/suggestion"
	  end
	  data = Array.new
	  (2..spreadsheet.last_row).each do |i|
	    row = Hash[[header, spreadsheet.row(i)].transpose].except!("DT")
	    # row.except!("DT")
	    # row["date_filed"] = row.delete "Timestamp"
	    # row["attribute"] = row.delete "What is your relationship to the vehicle?"
	    # row["rules"] = row.delete "What driving rules are you open for with your vehicle?"
	    # row["delivery"] = row.delete "What delivery options do you prefer?"
	    # row["car_name"] = row.delete "Vehicle Nickname"
	    # row["car_location"] = row.delete "Location of Vehicle"
	    # row["driver_location"] = row.delete "Location of Driver/s"
	    # row["vehicle_types"] = row.delete "Type of Vehicle"
	    # row["car_capacity"] = row.delete "Capacity"
	    # row["car_make"] = row.delete "Make"
	    # row["car_year"] = row.delete "Year"
	    # row["car_model"] = row.delete "Model"
	    # row["car_transmission"] = row.delete "Transmission"
	    # row["car_fuel"] = row.delete "Fuel"
	    # row["car_color"] = row.delete "Color"
	    # row["car_mileage"] = row.delete "Mileage (for automobiles)"
	    # row["car_other_feature"] = row.delete "Other features/specifications/uniqueness"
	    # row["payment_freq"] = row.delete "Payment Frequency"
	    # row["payment_method"] = row.delete "Payment Method"
	    # row["price_city"] = row.delete "Cost/Price for City Driving"
	    # row["price_province"] = row.delete "Cost/Price for Provincial Driving"
	    # row["cost_inclusion"] = row.delete "Cost inclusions"
	    # row["payment_condition"] = row.delete "Additional payment specifications"
	    # row["rules_addition"] = row.delete "Additional rules/preferences/notes for the renter"
	    # row["user_full_name"] = row.delete "Car Owner's Full Name"
	    # row["user_email"] = row.delete "Car Owner's Email"
	    # row["user_number"] = row.delete "Car Owner's Contact Number"
	    # row["logic"] = row.delete "Operator's Name"
	    # row["logic"] = row.delete "Operator's Contact Information"
	    # row["user_comment"] = row.delete "Additional comment/request/suggestion"

	    data << row 
	    # user = User.where(email: row["Car Owner's Email"]) || User.new
	    # user.attributes = row.to_hash
	    # user.save!
	    # user.car
	  end
	  return data
	end

end

app/helpers/archives_helper.rb
module ArchivesHelper
end

app/views/archives/index.html.erb
<h2>Import Excel</h2>
Beepers Data
<%= form_tag file_import_path, method: :post, multipart: true do %>
  <%= file_field_tag :file %>
  <%= submit_tag "Import" %>
<% end %>


<% if @data %>
<h2>Archive</h2>
<table>
	<tr>
			<th>Timestamp</th>
			<th>What is your relationship to the vehicle?</th>
			<th>What driving rules are you open for with your vehicle?</th>
			<th>What delivery options do you prefer?</th>
			<th>Vehicle Nickname</th>
			<th>Location of Vehicle</th>
			<th>Location of Driver/s</th>
			<th>Type of Vehicle</th>
			<th>Capacity</th>
			<th>Make</th>
			<th>Year</th>
			<th>Model</th>
			<th>Transmission</th>
			<th>Fuel</th>
			<th>Color</th>
			<th>Mileage (for automobiles)</th>
			<th>Other features/specifications/uniqueness</th>
			<th>Payment Frequency</th>
			<th>Payment Method</th>
			<th>Cost/Price for City Driving</th>
			<th>Cost/Price for Provincial Driving</th>
			<th>Cost inclusions</th>
			<th>Additional payment specifications</th>
			<th>Additional rules/preferences/notes for the renter</th>
			<th>Car Owner's Full Name</th>
			<th>Car Owner's Email</th>
			<th>Car Owner's Contact Number</th>
			<th>Operator's Name</th>
			<th>Operator's Contact Information</th>
			<th>Additional comment/request/suggestion</th>
	</tr>
	<% @data.each do |row| %>
	<tr>
		<td><%= row["date_filed"] %></td>
		<td><%= row["attribute"] %></td>
		<td><%= row["rules"] %></td>
		<td><%= row["delivery"] %></td>
		<td><%= row["car_name"] %></td>
		<td><%= row["car_location"] %></td>
		<td><%= row["driver_location"] %></td>
		<td><%= row["vehicle_types"] %></td>
		<td><%= row["car_capacity"] %></td>
		<td><%= row["car_make"] %></td>
		<td><%= row["car_year"] %></td>
		<td><%= row["car_model"] %></td>
		<td><%= row["car_transmission"] %></td>
		<td><%= row["car_fuel"] %></td>
		<td><%= row["car_color"] %></td>
		<td><%= row["car_mileage"] %></td>
		<td><%= row["car_other_feature"] %></td>
		<td><%= row["payment_freq"] %></td>
		<td><%= row["payment_method"] %></td>
		<td><%= row["price_city"] %></td>
		<td><%= row["price_province"] %></td>
		<td><%= row["cost_inclusion"] %></td>
		<td><%= row["payment_condition"] %></td>
		<td><%= row["rules_addition"] %></td>
		<td><%= row["user_full_name"] %></td>
		<td><%= row["user_email"] %></td>
		<td><%= row["user_number"] %></td>
		<td><%= row["Operator's Name"] %></td>
		<td><%= row["Operator's Contact Information"] %></td>
		<td><%= row["user_comment"] %></td>
	</tr>
	<% end %>
</table>
<% end %>